
#define DT_DISK_SDHC0_BUS_ADDRESS           KENDRYTE_SPI_52000000_ZEPHYR_MMC_SPI_SLOT_0_BASE_ADDRESS
#define DT_DISK_SDHC0_BUS_NAME              KENDRYTE_SPI_52000000_ZEPHYR_MMC_SPI_SLOT_0_BUS_NAME
#define DT_DISK_SDHC0_CS_GPIOS_CONTROLLER   "gpiohs" 
#define DT_DISK_SDHC0_CS_GPIOS_PIN          7
